PROJECT:=CheatsheetCarbon

include makefile-latex/latex-std-dependence.mk
DEPS_MAIN_TEX:=${STYS_MINIMUS} ${CLSS_CHEATSHEET_CARBON}
DEPS_FIGS_TEX:=${STYS_MINIMUS} ${CLSS_STANDALONE_SILICON}

include makefile-latex/makefile-latex.mk
